// Code generated by aocgen; DO NOT EDIT.
package year2022

import (
	"strings"
)

type Day02 struct{}

// A/X => Rock
// B/Y => Paper
// C/Z => Scissors

var scoresPerThing = map[string]int{
	"X": 1,
	"Y": 2,
	"Z": 3,
}

var counterPartToWin = map[string]string{
	"C": "X",
	"A": "Y",
	"B": "Z",
}

var counterPartToDraw = map[string]string{
	"A": "X",
	"B": "Y",
	"C": "Z",
}

var counterPartToLose = map[string]string{
	"A": "Z",
	"B": "X",
	"C": "Y",
}

func (p Day02) PartA(lines []string) any {
	score := 0

	for _, line := range lines {
		bits := strings.Split(line, " ")
		opponent := bits[0]
		me := bits[1]
		score += scoresPerThing[me]
		if me == counterPartToWin[opponent] {
			score += 6
		} else if me == counterPartToDraw[opponent] {
			score += 3
		}
	}

	return score
}

func (p Day02) PartB(lines []string) any {
	score := 0

	for _, line := range lines {
		bits := strings.Split(line, " ")
		opponent := bits[0]
		me := bits[1]

		switch me {
		case "X":
			score += scoresPerThing[counterPartToLose[opponent]]
		case "Y":
			score += 3
			score += scoresPerThing[counterPartToDraw[opponent]]
		case "Z":
			score += 6
			score += scoresPerThing[counterPartToWin[opponent]]
		}
	}

	return score
}
