// Code generated by aocgen; DO NOT EDIT.
package year2020

import (
	"testing"

	"aocgen/pkg/aoc"
)

func Benchmark2020Day01(b *testing.B) {
	Init()
	input := aoc.TestInput(2020, 1)
	p := aoc.NewPuzzle(2020, 1)
	b.Run("PartA", func(b *testing.B) {
		b.ResetTimer()
		for i := 0; i < b.N; i++ {
			p.PartA(input)
		}
	})
	b.Run("PartB", func(b *testing.B) {
		b.ResetTimer()
		for i := 0; i < b.N; i++ {
			p.PartB(input)
		}
	})
}
func Benchmark2020Day02(b *testing.B) {
	Init()
	input := aoc.TestInput(2020, 2)
	p := aoc.NewPuzzle(2020, 2)
	b.Run("PartA", func(b *testing.B) {
		b.ResetTimer()
		for i := 0; i < b.N; i++ {
			p.PartA(input)
		}
	})
	b.Run("PartB", func(b *testing.B) {
		b.ResetTimer()
		for i := 0; i < b.N; i++ {
			p.PartB(input)
		}
	})
}
func Benchmark2020Day03(b *testing.B) {
	Init()
	input := aoc.TestInput(2020, 3)
	p := aoc.NewPuzzle(2020, 3)
	b.Run("PartA", func(b *testing.B) {
		b.ResetTimer()
		for i := 0; i < b.N; i++ {
			p.PartA(input)
		}
	})
	b.Run("PartB", func(b *testing.B) {
		b.ResetTimer()
		for i := 0; i < b.N; i++ {
			p.PartB(input)
		}
	})
}
func Benchmark2020Day04(b *testing.B) {
	Init()
	input := aoc.TestInput(2020, 4)
	p := aoc.NewPuzzle(2020, 4)
	b.Run("PartA", func(b *testing.B) {
		b.ResetTimer()
		for i := 0; i < b.N; i++ {
			p.PartA(input)
		}
	})
	b.Run("PartB", func(b *testing.B) {
		b.ResetTimer()
		for i := 0; i < b.N; i++ {
			p.PartB(input)
		}
	})
}
func Benchmark2020Day05(b *testing.B) {
	Init()
	input := aoc.TestInput(2020, 5)
	p := aoc.NewPuzzle(2020, 5)
	b.Run("PartA", func(b *testing.B) {
		b.ResetTimer()
		for i := 0; i < b.N; i++ {
			p.PartA(input)
		}
	})
	b.Run("PartB", func(b *testing.B) {
		b.ResetTimer()
		for i := 0; i < b.N; i++ {
			p.PartB(input)
		}
	})
}
func Benchmark2020Day06(b *testing.B) {
	Init()
	input := aoc.TestInput(2020, 6)
	p := aoc.NewPuzzle(2020, 6)
	b.Run("PartA", func(b *testing.B) {
		b.ResetTimer()
		for i := 0; i < b.N; i++ {
			p.PartA(input)
		}
	})
	b.Run("PartB", func(b *testing.B) {
		b.ResetTimer()
		for i := 0; i < b.N; i++ {
			p.PartB(input)
		}
	})
}
func Benchmark2020Day07(b *testing.B) {
	Init()
	input := aoc.TestInput(2020, 7)
	p := aoc.NewPuzzle(2020, 7)
	b.Run("PartA", func(b *testing.B) {
		b.ResetTimer()
		for i := 0; i < b.N; i++ {
			p.PartA(input)
		}
	})
	b.Run("PartB", func(b *testing.B) {
		b.ResetTimer()
		for i := 0; i < b.N; i++ {
			p.PartB(input)
		}
	})
}
func Benchmark2020Day08(b *testing.B) {
	Init()
	input := aoc.TestInput(2020, 8)
	p := aoc.NewPuzzle(2020, 8)
	b.Run("PartA", func(b *testing.B) {
		b.ResetTimer()
		for i := 0; i < b.N; i++ {
			p.PartA(input)
		}
	})
	b.Run("PartB", func(b *testing.B) {
		b.ResetTimer()
		for i := 0; i < b.N; i++ {
			p.PartB(input)
		}
	})
}
func Benchmark2020Day09(b *testing.B) {
	Init()
	input := aoc.TestInput(2020, 9)
	p := aoc.NewPuzzle(2020, 9)
	b.Run("PartA", func(b *testing.B) {
		b.ResetTimer()
		for i := 0; i < b.N; i++ {
			p.PartA(input)
		}
	})
	b.Run("PartB", func(b *testing.B) {
		b.ResetTimer()
		for i := 0; i < b.N; i++ {
			p.PartB(input)
		}
	})
}
func Benchmark2020Day10(b *testing.B) {
	Init()
	input := aoc.TestInput(2020, 10)
	p := aoc.NewPuzzle(2020, 10)
	b.Run("PartA", func(b *testing.B) {
		b.ResetTimer()
		for i := 0; i < b.N; i++ {
			p.PartA(input)
		}
	})
	b.Run("PartB", func(b *testing.B) {
		b.ResetTimer()
		for i := 0; i < b.N; i++ {
			p.PartB(input)
		}
	})
}
func Benchmark2020Day11(b *testing.B) {
	Init()
	input := aoc.TestInput(2020, 11)
	p := aoc.NewPuzzle(2020, 11)
	b.Run("PartA", func(b *testing.B) {
		b.ResetTimer()
		for i := 0; i < b.N; i++ {
			p.PartA(input)
		}
	})
	b.Run("PartB", func(b *testing.B) {
		b.ResetTimer()
		for i := 0; i < b.N; i++ {
			p.PartB(input)
		}
	})
}
func Benchmark2020Day12(b *testing.B) {
	Init()
	input := aoc.TestInput(2020, 12)
	p := aoc.NewPuzzle(2020, 12)
	b.Run("PartA", func(b *testing.B) {
		b.ResetTimer()
		for i := 0; i < b.N; i++ {
			p.PartA(input)
		}
	})
	b.Run("PartB", func(b *testing.B) {
		b.ResetTimer()
		for i := 0; i < b.N; i++ {
			p.PartB(input)
		}
	})
}
